// ========================================
// ASSIGNMENTS PAGE + ASSIGNMENT FIELDS
// ========================================
function getAssignmentData(){return{tasks:Array.isArray(plannerData?.tasks)?plannerData.tasks:[],subjects:Array.isArray(plannerData?.settings?.subjects)?plannerData.settings.subjects:[]};}
function populateAssignmentSubjects(id){const e=document.querySelector(id);if(!e)return;const cur=e.value;e.innerHTML=`<option value="">${id==='#assignmentSubject'?'Choose a subject':'All subjects'}</option>`;getAssignmentData().subjects.filter(s=>s&&s.active!==false).forEach(s=>{const o=document.createElement('option');o.value=s.name||'';o.textContent=`${s.emoji||'📚'} ${s.name||''}`;e.appendChild(o)});if([...e.options].some(o=>o.value===cur))e.value=cur;}
function openAssignmentModal(){const m=document.querySelector('#assignmentModal');if(!m)return;populateAssignmentSubjects('#assignmentSubject');['#assignmentName','#assignmentDueDate','#assignmentWeight','#assignmentNotes'].forEach(id=>{const e=document.querySelector(id);if(e)e.value=''});document.querySelector('#assignmentPriority').value='Normal';m.classList.add('open');document.querySelector('#assignmentName')?.focus();}
function closeAssignmentModal(){document.querySelector('#assignmentModal')?.classList.remove('open');}
function createAssignment(){const name=document.querySelector('#assignmentName')?.value.trim();if(!name){alert('Please enter an assignment name.');return;}plannerData.tasks.push({id:Date.now(),name,subject:document.querySelector('#assignmentSubject')?.value||'',type:'Assignment',priority:document.querySelector('#assignmentPriority')?.value||'Normal',dueDate:document.querySelector('#assignmentDueDate')?.value||null,tags:['#School'],notes:document.querySelector('#assignmentNotes')?.value.trim()||'',weight:document.querySelector('#assignmentWeight')?.value||'',completed:false,createdAt:new Date().toISOString()});savePlannerData();closeAssignmentModal();renderAssignments();if(typeof renderTasks==='function')renderTasks();if(typeof renderCalendar==='function')renderCalendar();if(typeof renderAllTasks==='function')renderAllTasks();}
function assignmentState(t){if(t.completed||String(t.status||'').toLowerCase()==='completed')return'completed';if(t.dueDate&&new Date(String(t.dueDate).slice(0,10)+'T00:00:00')<new Date(new Date().toDateString()))return'overdue';return'upcoming';}
function renderAssignments(){const list=document.querySelector('#assignmentsList');if(!list)return;const{tasks,subjects}=getAssignmentData(),a=tasks.filter(t=>String(t.type||'').toLowerCase()==='assignment');populateAssignmentSubjects('#assignmentSubjectFilter');const sf=document.querySelector('#assignmentSubjectFilter')?.value||'',st=document.querySelector('#assignmentStatusFilter')?.value||'',filtered=a.filter(t=>(!sf||t.subject===sf)&&(!st||assignmentState(t)===st)).sort((x,y)=>String(x.dueDate||'9999-12-31').localeCompare(String(y.dueDate||'9999-12-31')));document.querySelector('#assignmentUpcomingCount').textContent=a.filter(t=>assignmentState(t)==='upcoming').length;document.querySelector('#assignmentOverdueCount').textContent=a.filter(t=>assignmentState(t)==='overdue').length;document.querySelector('#assignmentCompletedCount').textContent=a.filter(t=>assignmentState(t)==='completed').length;list.innerHTML='';if(!filtered.length){list.innerHTML='<div class="empty-assignments">No assignments match your filters.</div>';return;}filtered.forEach(t=>{const s=subjects.find(x=>x.name===t.subject),r=document.createElement('div');r.className='assignment-row '+assignmentState(t);r.dataset.taskId=t.id;if(s?.colour)r.style.setProperty('--assignment-color',s.colour);r.innerHTML='<span class="assignment-icon"></span><span class="assignment-main"><strong></strong><small></small></span><span class="assignment-meta"><span class="assignment-due"></span><span class="assignment-weight"></span><button type="button" class="record-grade-button">Record Grade</button></span>';r.querySelector('.assignment-icon').textContent=s?.emoji||'📝';r.querySelector('strong').textContent=t.name||'Untitled assignment';r.querySelector('small').textContent=t.subject||'No subject';r.querySelector('.assignment-due').textContent=t.dueDate?`Due ${t.dueDate}`:'No due date';r.querySelector('.assignment-weight').textContent=t.weight!==''&&t.weight!=null?`${t.weight}%`:'';r.onclick=e=>{if(e.target.closest('.record-grade-button'))return;if(typeof openEditTaskModal==='function')openEditTaskModal(t.id)};r.querySelector('.record-grade-button').onclick=e=>{e.stopPropagation();if(typeof window.openGradeModal==='function'){window.openGradeModal();const sel=document.querySelector('#gradeTask');if(sel){sel.value=String(t.id);sel.dispatchEvent(new Event('change'));}}};list.appendChild(r);});}
function addAssignmentFieldsToTaskModal(){const type=document.querySelector('#taskType'),modal=document.querySelector('#taskModal .modal');if(!type||!modal||document.querySelector('#taskAssignmentFields'))return;const box=document.createElement('div');box.id='taskAssignmentFields';box.className='assignment-extra-fields';box.innerHTML='<div class="form-group"><label for="taskAssignmentWeight">Weight</label><div class="percentage-input"><input id="taskAssignmentWeight" type="number" min="0" max="100" step="0.1" placeholder="0"><span>%</span></div></div><div class="form-group"><label for="taskAssignmentNotes">Notes</label><textarea id="taskAssignmentNotes" rows="3" placeholder="Instructions or notes..."></textarea></div>';const tags=document.querySelector('#taskTags')?.closest('.form-group');if(tags)tags.after(box);function update(){box.style.display=String(type.value).toLowerCase()==='assignment'?'block':'none';}type.addEventListener('change',update);update();}
document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#assignmentSubjectFilter')?.addEventListener('change',renderAssignments);document.querySelector('#assignmentStatusFilter')?.addEventListener('change',renderAssignments);addAssignmentFieldsToTaskModal();});
