// ========================================
// CALENDAR
// ========================================
let calendarDate = new Date();
let calendarView = 'month';
const CALENDAR_DAY_START = 6;
const CALENDAR_DAY_END = 23;

function calendarPreviousMonth(){if(calendarView==='week')calendarDate=new Date(calendarDate.getTime()-7*86400000);else if(calendarView==='day')calendarDate=new Date(calendarDate.getTime()-86400000);else calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1);renderCalendar();}
function calendarNextMonth(){if(calendarView==='week')calendarDate=new Date(calendarDate.getTime()+7*86400000);else if(calendarView==='day')calendarDate=new Date(calendarDate.getTime()+86400000);else calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1);renderCalendar();}
function calendarGoToToday(){calendarDate=new Date();renderCalendar();}
function calendarSetView(view){if(['month','week','day'].includes(view))calendarView=view;renderCalendar();}
function getPlannerTasksForCalendar(){return typeof plannerData!=='undefined'&&Array.isArray(plannerData.tasks)?plannerData.tasks:[];}
function getCalendarSubjects(){return typeof plannerData!=='undefined'&&plannerData.settings?.subjects?plannerData.settings.subjects:[];}
function getCalendarEvents(){return typeof plannerData!=='undefined'&&Array.isArray(plannerData.events)?plannerData.events:[];}
function calendarDateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function calendarRecurringDateMatches(task,dateString){const start=new Date(String(task.dueDate).slice(0,10)+'T00:00:00'),target=new Date(dateString+'T00:00:00');if(Number.isNaN(start.getTime())||target<start)return false;const diff=Math.floor((target-start)/86400000),day=Number(task.recurrenceDay??start.getDay()),r=task.recurrence;if(r==='daily')return true;if(r==='weekday')return target.getDay()>0&&target.getDay()<6;if(r==='weekly')return target.getDay()===day&&diff%7===0;if(r==='biweekly')return target.getDay()===day&&diff%14===0;if(r==='monthly'){const wanted=Number(task.recurrenceMonthDay||start.getDate());return target.getDate()===Math.min(wanted,new Date(target.getFullYear(),target.getMonth()+1,0).getDate());}if(r==='custom'){const n=Math.max(1,Number(task.recurrenceInterval)||1);if(task.recurrenceUnit==='weeks')return diff%(n*7)===0;if(task.recurrenceUnit==='months'){const months=(target.getFullYear()-start.getFullYear())*12+target.getMonth()-start.getMonth();return target.getDate()===start.getDate()&&months>=0&&months%n===0;}return diff%n===0;}return false;}
function getCalendarTasksForDate(tasks,date){return tasks.filter(t=>(t.dueDate&&String(t.dueDate).slice(0,10)===date)||calendarRecurringDateMatches(t,date));}
function getCalendarEventsForDate(events,date){return events.filter(e=>{const start=String(e.date||'').slice(0,10),end=String(e.endDate||e.date||'').slice(0,10);return start&&date>=start&&date<=end;});}
function openCalendarTask(taskId){if(typeof window.openEditTaskModal==='function')return window.openEditTaskModal(taskId);if(typeof window.openCalendarTask==='function')return window.openCalendarTask(taskId);}
function ensureCalendarTaskTimeField(){const due=document.querySelector('#taskDueDate');if(!due||document.querySelector('#taskTime'))return;const group=due.closest('.form-group');if(!group)return;const timeGroup=document.createElement('div');timeGroup.className='form-group';timeGroup.innerHTML='<label for="taskTime">Time <span style="font-weight:normal;opacity:.65">(optional)</span></label><input id="taskTime" type="time">';group.parentElement?.appendChild(timeGroup);}
function createCalendarTask(date,time=''){if(typeof window.openTaskModal!=='function')return;ensureCalendarTaskTimeField();window.openTaskModal();const d=document.querySelector('#taskDueDate');if(d)d.value=date;const t=document.querySelector('#taskTime');if(t)t.value=time;}
function calendarFormatHour(hour){const suffix=hour>=12?'PM':'AM',h=hour%12||12;return `${h}:00 ${suffix}`;}
function ensureCalendarChooser(){if(document.getElementById('calendarAddChoice'))return;const wrap=document.createElement('div');wrap.className='modal-overlay';wrap.id='calendarAddChoice';wrap.innerHTML='<div class="modal calendar-add-choice"><div class="modal-header"><h2>Add to calendar</h2><button class="close-button" type="button" id="calendarChoiceClose">×</button></div><p>What would you like to add?</p><div class="calendar-choice-buttons"><button type="button" id="calendarChoiceTask">✓ Task</button><button type="button" id="calendarChoiceEvent">📅 Event</button></div></div>';document.body.appendChild(wrap);document.getElementById('calendarChoiceClose').onclick=()=>wrap.classList.remove('open');}
function openCalendarAddChoice(date,time=''){ensureCalendarChooser();const wrap=document.getElementById('calendarAddChoice');wrap.classList.add('open');document.getElementById('calendarChoiceTask').onclick=()=>{wrap.classList.remove('open');createCalendarTask(date,time);};document.getElementById('calendarChoiceEvent').onclick=()=>{wrap.classList.remove('open');if(typeof openEventModal==='function'){openEventModal(null,date);const input=document.getElementById('eventTime');if(input)input.value=time;}};}
function calendarInjectStyles(){if(document.getElementById('calendarDayViewStyles'))return;const s=document.createElement('style');s.id='calendarDayViewStyles';s.textContent=`.calendar-week-view,.calendar-day-view{display:grid!important;grid-template-columns:repeat(var(--calendar-cols,7),minmax(0,1fr));gap:0;overflow:auto}.calendar-day-view{--calendar-cols:1}.calendar-view-column{min-width:0;border:1px solid var(--border-color,#e5e7eb);background:var(--card-bg,#fff)}.calendar-view-header{padding:12px;text-align:center;font-weight:600;border-bottom:1px solid var(--border-color,#e5e7eb);position:sticky;top:0;background:inherit;z-index:2}.calendar-view-header.today{font-weight:800}.calendar-time-grid{display:grid;grid-template-columns:72px 1fr;min-height:1296px}.calendar-times{font-size:12px;color:#777}.calendar-time-label{height:72px;padding:5px 8px;text-align:right;border-bottom:1px solid #eee;box-sizing:border-box}.calendar-time-slots{position:relative}.calendar-time-slot{height:72px;border-bottom:1px solid #eee;box-sizing:border-box;cursor:pointer;position:relative}.calendar-time-slot:hover{background:rgba(124,58,237,.06)}.calendar-time-item{position:absolute;left:6px;right:6px;min-height:28px;padding:5px 8px;border-radius:7px;border-left:4px solid var(--item-color,#7c3aed);background:rgba(124,58,237,.10);font-size:13px;overflow:hidden;text-align:left;z-index:1}.calendar-time-item.completed{opacity:.55;text-decoration:line-through}.calendar-time-item.event{border-left-color:var(--event-color,#7c3aed)}.calendar-add-choice{max-width:380px}.calendar-choice-buttons{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:16px}.calendar-choice-buttons button{padding:14px;border:1px solid #ddd;border-radius:10px;background:transparent;font-size:16px;cursor:pointer}.calendar-choice-buttons button:hover{background:rgba(124,58,237,.08)}.calendar-view-day-items{padding:8px}.calendar-view-day-items .calendar-event,.calendar-view-day-items .calendar-task{display:block;width:100%;margin-bottom:6px;text-align:left}`;document.head.appendChild(s);}
function positionTimedItem(item,time,slots){if(!time){item.style.position='relative';item.style.margin='6px';slots.appendChild(item);return;}const parts=String(time).split(':'),h=Number(parts[0]),min=Number(parts[1]||0);const offset=Math.max(0,(h-CALENDAR_DAY_START)*72+min*1.2);item.style.top=offset+'px';item.style.height='40px';slots.appendChild(item);}
function renderTimedDay(date,tasks,events,subjects){calendarInjectStyles();const column=document.createElement('div');column.className='calendar-view-column';const header=document.createElement('div');header.className='calendar-view-header';header.textContent=date.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});if(calendarDateKey(date)===calendarDateKey(new Date()))header.classList.add('today');column.appendChild(header);const grid=document.createElement('div');grid.className='calendar-time-grid';const times=document.createElement('div');times.className='calendar-times';const slots=document.createElement('div');slots.className='calendar-time-slots';for(let h=CALENDAR_DAY_START;h<=CALENDAR_DAY_END;h++){const label=document.createElement('div');label.className='calendar-time-label';label.textContent=calendarFormatHour(h);times.appendChild(label);const slot=document.createElement('div');slot.className='calendar-time-slot';slot.dataset.time=`${String(h).padStart(2,'0')}:00`;slot.onclick=()=>openCalendarAddChoice(calendarDateKey(date),slot.dataset.time);slots.appendChild(slot);}grid.append(times,slots);column.appendChild(grid);const key=calendarDateKey(date);
 getCalendarEventsForDate(events,key).forEach(e=>{const item=document.createElement('button');item.type='button';item.className='calendar-time-item event';item.style.setProperty('--event-color',e.colour||'#7c3aed');item.textContent=`${e.time||'All day'} · ${e.name||'Untitled event'}`;item.onclick=x=>{x.stopPropagation();if(typeof openEventModal==='function')openEventModal(e.id);};positionTimedItem(item,e.time,slots);});
 getCalendarTasksForDate(tasks,key).forEach(t=>{const item=document.createElement('button');item.type='button';item.className='calendar-time-item';if(t.completed||t.status==='Completed')item.classList.add('completed');const sub=subjects.find(x=>x.name===t.subject);item.style.setProperty('--item-color',sub?.colour||'#7c3aed');item.textContent=`${sub?.emoji||'✓'} ${t.name||'Untitled task'}${t.recurrence?' ↻':''}`;item.onclick=x=>{x.stopPropagation();openCalendarTask(t.id);};if(t.time)positionTimedItem(item,t.time,slots);else{item.style.position='relative';item.style.margin='6px';item.style.display='block';item.style.width='calc(100% - 12px)';slots.prepend(item);}});return column;}
function renderCalendar(){const title=document.querySelector('#calendarMonthTitle'),grid=document.querySelector('#calendarGrid');if(!title||!grid)return;ensureCalendarTaskTimeField();const tasks=getPlannerTasksForCalendar(),events=getCalendarEvents(),subjects=getCalendarSubjects();grid.innerHTML='';grid.className='calendar-grid';
 if(calendarView==='month'){const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1).getDay(),count=new Date(y,m+1,0).getDate(),today=new Date();title.textContent=calendarDate.toLocaleDateString(undefined,{month:'long',year:'numeric'});for(let i=0;i<first;i++){const b=document.createElement('div');b.className='calendar-day calendar-day-empty';grid.appendChild(b);}for(let day=1;day<=count;day++){const cell=document.createElement('div');cell.className='calendar-day';if(day===today.getDate()&&m===today.getMonth()&&y===today.getFullYear())cell.classList.add('today');const num=document.createElement('div');num.className='calendar-day-number';num.textContent=day;cell.appendChild(num);const date=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;getCalendarEventsForDate(events,date).slice(0,3).forEach(e=>{const item=document.createElement('button');item.type='button';item.className='calendar-event';item.style.setProperty('--event-color',e.colour||'#7c3aed');if(String(e.date).slice(0,10)===date)item.classList.add('event-start');else item.classList.add('event-continuation');item.textContent=`• ${e.name||'Untitled event'}${e.time&&String(e.date).slice(0,10)===date?' · '+e.time:''}`;item.onclick=x=>{x.stopPropagation();if(typeof openEventModal==='function')openEventModal(e.id);};cell.appendChild(item);});getCalendarTasksForDate(tasks,date).slice(0,4).forEach(t=>{const item=document.createElement('button');item.type='button';item.className='calendar-task';if(t.completed||t.status==='Completed')item.classList.add('completed');const s=subjects.find(x=>x.name===t.subject);if(s?.colour)item.style.setProperty('--task-color',s.colour);item.textContent=`${s?.emoji||'✓'} ${t.name||'Untitled task'}${t.recurrence?' ↻':''}`;item.onclick=e=>{e.stopPropagation();openCalendarTask(t.id);};cell.appendChild(item);});cell.addEventListener('click',()=>openCalendarAddChoice(date));grid.appendChild(cell);}return;}
 const base=new Date(calendarDate.getFullYear(),calendarDate.getMonth(),calendarDate.getDate());let dates=[];if(calendarView==='week'){const sunday=new Date(base);sunday.setDate(base.getDate()-base.getDay());dates=Array.from({length:7},(_,i)=>new Date(sunday.getFullYear(),sunday.getMonth(),sunday.getDate()+i));title.textContent=`${dates[0].toLocaleDateString(undefined,{month:'short',day:'numeric'})} – ${dates[6].toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}`;grid.style.setProperty('--calendar-cols','7');dates.forEach(d=>grid.appendChild(renderTimedDay(d,tasks,events,subjects)));return;}
 title.textContent=base.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});grid.style.setProperty('--calendar-cols','1');grid.appendChild(renderTimedDay(base,tasks,events,subjects));}

(function installCalendarViewControls(){function install(){const title=document.querySelector('#calendarMonthTitle');if(!title)return;let controls=document.querySelector('#calendarViewControls');if(!controls){controls=document.createElement('div');controls.id='calendarViewControls';controls.className='calendar-view-controls';[['month','Month'],['week','Week'],['day','Day']].forEach(([v,label])=>{const b=document.createElement('button');b.type='button';b.dataset.view=v;b.textContent=label;b.onclick=()=>calendarSetView(v);controls.appendChild(b);});title.parentElement?.appendChild(controls);}controls.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.view===calendarView));ensureCalendarChooser();}document.addEventListener('DOMContentLoaded',install);window.addEventListener('load',install);setInterval(install,500);})();

if(!window.__calendarEventsScriptLoaded){window.__calendarEventsScriptLoaded=true;const s=document.createElement('script');s.src='calendar-events.js';document.head.appendChild(s);}
