// ========================================
// CALENDAR
// ========================================
let calendarDate = new Date();
let calendarView = 'month';
function calendarPreviousMonth(){if(calendarView==='week')calendarDate=new Date(calendarDate.getTime()-7*86400000);else if(calendarView==='day')calendarDate=new Date(calendarDate.getTime()-86400000);else calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1);renderCalendar();}
function calendarNextMonth(){if(calendarView==='week')calendarDate=new Date(calendarDate.getTime()+7*86400000);else if(calendarView==='day')calendarDate=new Date(calendarDate.getTime()+86400000);else calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1);renderCalendar();}
function calendarGoToToday(){calendarDate=new Date();renderCalendar();}
function calendarSetView(view){if(['month','week','day'].includes(view))calendarView=view;renderCalendar();}
function getPlannerTasksForCalendar(){return typeof plannerData!=='undefined'&&Array.isArray(plannerData.tasks)?plannerData.tasks:[];}
function getCalendarSubjects(){return typeof plannerData!=='undefined'&&plannerData.settings?.subjects?plannerData.settings.subjects:[];}
function getCalendarEvents(){return typeof plannerData!=='undefined'&&Array.isArray(plannerData.events)?plannerData.events:[];}
function calendarRecurringDateMatches(task,dateString){const start=new Date(String(task.dueDate).slice(0,10)+'T00:00:00'),target=new Date(dateString+'T00:00:00');if(Number.isNaN(start.getTime())||target<start)return false;const diff=Math.floor((target-start)/86400000),day=Number(task.recurrenceDay??start.getDay()),r=task.recurrence;if(r==='daily')return true;if(r==='weekday')return target.getDay()>0&&target.getDay()<6;if(r==='weekly')return target.getDay()===day&&diff%7===0;if(r==='biweekly')return target.getDay()===day&&diff%14===0;if(r==='monthly'){const wanted=Number(task.recurrenceMonthDay||start.getDate());return target.getDate()===Math.min(wanted,new Date(target.getFullYear(),target.getMonth()+1,0).getDate());}if(r==='custom'){const n=Math.max(1,Number(task.recurrenceInterval)||1);if(task.recurrenceUnit==='weeks')return diff%(n*7)===0;if(task.recurrenceUnit==='months'){const months=(target.getFullYear()-start.getFullYear())*12+target.getMonth()-start.getMonth();return target.getDate()===start.getDate()&&months>=0&&months%n===0;}return diff%n===0;}return false;}
function getCalendarTasksForDate(tasks,date){return tasks.filter(t=>(t.dueDate&&String(t.dueDate).slice(0,10)===date)||calendarRecurringDateMatches(t,date));}
function getCalendarEventsForDate(events,date){return events.filter(e=>{const start=String(e.date||'').slice(0,10),end=String(e.endDate||e.date||'').slice(0,10);return start&&date>=start&&date<=end;});}
function openCalendarTask(taskId){if(typeof window.openEditTaskModal==='function')return window.openEditTaskModal(taskId);if(typeof window.openCalendarTask==='function')return window.openCalendarTask(taskId);}
function createCalendarTask(date){if(typeof window.openTaskModal!=='function')return;window.openTaskModal();const d=document.querySelector('#taskDueDate');if(d)d.value=date;}
function calendarDateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function calendarDayItems(date,tasks,events,subjects){const key=calendarDateKey(date),wrap=document.createElement('div');wrap.className='calendar-view-day-items';getCalendarEventsForDate(events,key).forEach(e=>{const item=document.createElement('button');item.type='button';item.className='calendar-event';item.style.setProperty('--event-color',e.colour||'#7c3aed');item.textContent=`• ${e.name||'Untitled event'}${e.time?' · '+e.time:''}`;item.onclick=x=>{x.stopPropagation();if(typeof openEventModal==='function')openEventModal(e.id);};wrap.appendChild(item);});getCalendarTasksForDate(tasks,key).forEach(t=>{const item=document.createElement('button');item.type='button';item.className='calendar-task';if(t.completed||t.status==='Completed')item.classList.add('completed');const s=subjects.find(x=>x.name===t.subject);if(s?.colour)item.style.setProperty('--task-color',s.colour);item.textContent=`${s?.emoji||'✓'} ${t.name||'Untitled task'}${t.recurrence?' ↻':''}`;item.onclick=x=>{x.stopPropagation();openCalendarTask(t.id);};wrap.appendChild(item);});wrap.addEventListener('click',()=>createCalendarTask(key));return wrap;}
function renderCalendar(){const title=document.querySelector('#calendarMonthTitle'),grid=document.querySelector('#calendarGrid');if(!title||!grid)return;const tasks=getPlannerTasksForCalendar(),events=getCalendarEvents(),subjects=getCalendarSubjects();grid.innerHTML='';
 const view=calendarView;
 if(view==='month'){const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1).getDay(),count=new Date(y,m+1,0).getDate(),today=new Date();title.textContent=calendarDate.toLocaleDateString(undefined,{month:'long',year:'numeric'});for(let i=0;i<first;i++){const b=document.createElement('div');b.className='calendar-day calendar-day-empty';grid.appendChild(b);}for(let day=1;day<=count;day++){const cell=document.createElement('div');cell.className='calendar-day';if(day===today.getDate()&&m===today.getMonth()&&y===today.getFullYear())cell.classList.add('today');const num=document.createElement('div');num.className='calendar-day-number';num.textContent=day;cell.appendChild(num);const date=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;getCalendarEventsForDate(events,date).slice(0,3).forEach(e=>{const item=document.createElement('button');item.type='button';item.className='calendar-event';item.style.setProperty('--event-color',e.colour||'#7c3aed');if(String(e.date).slice(0,10)===date)item.classList.add('event-start');else item.classList.add('event-continuation');item.textContent=`• ${e.name||'Untitled event'}${e.time&&String(e.date).slice(0,10)===date?' · '+e.time:''}`;item.onclick=x=>{x.stopPropagation();if(typeof openEventModal==='function')openEventModal(e.id);};cell.appendChild(item);});getCalendarTasksForDate(tasks,date).slice(0,4).forEach(t=>{const item=document.createElement('button');item.type='button';item.className='calendar-task';if(t.completed||t.status==='Completed')item.classList.add('completed');const s=subjects.find(x=>x.name===t.subject);if(s?.colour)item.style.setProperty('--task-color',s.colour);item.textContent=`${s?.emoji||'✓'} ${t.name||'Untitled task'}${t.recurrence?' ↻':''}`;item.onclick=e=>{e.stopPropagation();openCalendarTask(t.id);};cell.appendChild(item);});cell.addEventListener('click',()=>createCalendarTask(date));grid.appendChild(cell);}return;}
 const base=new Date(calendarDate.getFullYear(),calendarDate.getMonth(),calendarDate.getDate());let dates=[];if(view==='week'){const sunday=new Date(base);sunday.setDate(base.getDate()-base.getDay());dates=Array.from({length:7},(_,i)=>new Date(sunday.getFullYear(),sunday.getMonth(),sunday.getDate()+i));title.textContent=`${dates[0].toLocaleDateString(undefined,{month:'short',day:'numeric'})} – ${dates[6].toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}`;}else{dates=[base];title.textContent=base.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});}
 grid.className='calendar-grid calendar-'+view+'-view';dates.forEach(d=>{const col=document.createElement('div');col.className='calendar-view-column';const head=document.createElement('div');head.className='calendar-view-header';head.textContent=d.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});if(calendarDateKey(d)===calendarDateKey(new Date()))head.classList.add('today');col.appendChild(head);col.appendChild(calendarDayItems(d,tasks,events,subjects));grid.appendChild(col);});
}

(function installCalendarViewControls(){function install(){const title=document.querySelector('#calendarMonthTitle');if(!title)return;let controls=document.querySelector('#calendarViewControls');if(!controls){controls=document.createElement('div');controls.id='calendarViewControls';controls.className='calendar-view-controls';const views=[['month','Month'],['week','Week'],['day','Day']];views.forEach(([v,label])=>{const b=document.createElement('button');b.type='button';b.dataset.view=v;b.textContent=label;b.onclick=()=>calendarSetView(v);controls.appendChild(b);});title.parentElement?.appendChild(controls);}controls.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.view===calendarView));}document.addEventListener('DOMContentLoaded',install);window.addEventListener('load',install);setInterval(install,500);})();

if(!window.__calendarEventsScriptLoaded){window.__calendarEventsScriptLoaded=true;const s=document.createElement('script');s.src='calendar-events.js';document.head.appendChild(s);}
