// ========================================
// GRADES PAGE — ONTARIO-STYLE 70/30 TRACKER
// ========================================
(function(){
  window.__gradesPageLoaded=true;
  const CATEGORIES=['Knowledge','Communication','Thinking','Application'];
  const LEVELS=['1-','1','1+','2-','2','2+','3-','3','3+','4-','4','4+','4++'];
  const LEVEL_PERCENT={'1-':40,'1':45,'1+':50,'2-':55,'2':60,'2+':65,'3-':70,'3':75,'3+':80,'4-':85,'4':90,'4+':95,'4++':100};
  function el(id){return document.getElementById(id);}
  function activeSubjects(){return (plannerData.settings?.subjects||[]).filter(s=>s&&s.active!==false);}
  function ensureData(){
    if(!Array.isArray(plannerData.gradeAssessments))plannerData.gradeAssessments=[];
    if(!plannerData.gradeSettings)plannerData.gradeSettings={};
    activeSubjects().forEach(s=>{if(!plannerData.gradeSettings[s.name])plannerData.gradeSettings[s.name]={knowledge:25,communication:25,thinking:25,application:25};});
  }
  function schoolwork(){return (plannerData.tasks||[]).filter(t=>['assignment','quiz','test','exam','lab'].includes(String(t.type||'').toLowerCase())||((t.tags||[]).some(x=>String(x).toLowerCase()==='#school')));}
  function populateSubjects(id,all){const s=el(id);if(!s)return;const cur=s.value;s.innerHTML=all?'<option value="">All subjects</option>':'<option value="">Choose a subject</option>';activeSubjects().forEach(x=>{const o=document.createElement('option');o.value=x.name;o.textContent=`${x.emoji||'📚'} ${x.name}`;s.appendChild(o);});if([...s.options].some(o=>o.value===cur))s.value=cur;}
  function populateTaskLinks(){const s=el('gradeTask');if(!s)return;const cur=s.value;s.innerHTML='<option value="">New / not linked to schoolwork</option>';schoolwork().sort((a,b)=>String(b.dueDate||b.createdAt||'').localeCompare(String(a.dueDate||a.createdAt||''))).forEach(t=>{const o=document.createElement('option');o.value=String(t.id);o.textContent=`${t.subject||'No subject'} — ${t.name||'Untitled'} (${t.type||'Task'})`;o.dataset.name=t.name||'';o.dataset.subject=t.subject||'';o.dataset.type=t.type||'';o.dataset.weight=t.weight??'';o.dataset.notes=t.notes||'';s.appendChild(o);});if([...s.options].some(o=>o.value===cur))s.value=cur;}
  function linkTask(){const o=el('gradeTask')?.selectedOptions?.[0];if(!o||!o.value)return;el('gradeName').value=o.dataset.name||'';el('gradeSubject').value=o.dataset.subject||'';const type=o.dataset.type||'';if(type&&[...el('gradeType')?.options||[]].some(x=>x.value.toLowerCase()===type.toLowerCase()))el('gradeType').value=[...el('gradeType').options].find(x=>x.value.toLowerCase()===type.toLowerCase()).value;const linkedWeight=o.dataset.weight||'';const linkedNotes=o.dataset.notes||'';if(el('gradeItemWeight'))el('gradeItemWeight').value=linkedWeight;if(el('gradeNotes'))el('gradeNotes').value=linkedNotes;}
  function parsePoints(v){const m=String(v||'').trim().match(/^(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)$/);if(!m)return null;const earned=Number(m[1]),possible=Number(m[2]);if(possible<=0)return null;return{display:`${earned}/${possible}`,percent:Math.max(0,Math.min(100,earned/possible*100)),kind:'points',earned,possible};}
  function parseLevel(v){const x=String(v||'').trim();return LEVEL_PERCENT[x]!=null?{display:x,percent:LEVEL_PERCENT[x],kind:'level'}:null;}
  function readMark(format,value){return format==='level'?parseLevel(value):parsePoints(value);}
  function categoryInput(c){return `<div class="category-grade-row"><div class="category-name"><strong>${c}</strong><small>Achievement category</small></div><select class="category-format" data-category="${c}"><option value="points">Points (x/x)</option><option value="level">Level (0–4++)</option></select><div class="category-value"><input class="category-points" data-category="${c}" type="text" placeholder="e.g. 17/20"><select class="category-level" data-category="${c}" style="display:none"><option value="">Select level</option>${LEVELS.map(x=>`<option value="${x}">${x}</option>`).join('')}</select></div></div>`;}
  function renderCategoryInputs(){const b=el('categoryGradeBox');b.innerHTML=`<div class="category-grade-heading"><strong>Achievement categories</strong><span>Leave unused categories blank.</span></div>${CATEGORIES.map(categoryInput).join('')}`;b.querySelectorAll('.category-format').forEach(s=>s.onchange=()=>{const c=s.dataset.category,p=b.querySelector(`.category-points[data-category="${c}"]`),l=b.querySelector(`.category-level[data-category="${c}"]`),yes=s.value==='level';p.style.display=yes?'none':'block';l.style.display=yes?'block':'none';});}
  function renderTotalInput(){el('totalGradeBox').innerHTML='<div class="total-grade-fields"><div class="form-group"><label for="gradeTotalValue">Mark</label><input id="gradeTotalValue" type="text" placeholder="e.g. 42/50 or 3+"></div><div class="form-group"><label for="gradeTotalFormat">Format</label><select id="gradeTotalFormat"><option value="points">Points (x/x)</option><option value="level">Level (0–4++)</option></select></div></div>';}
  function renderGradeInputMode(){const m=document.querySelector('input[name="gradeMode"]:checked')?.value||'categories';el('categoryGradeBox').style.display=m==='categories'?'block':'none';el('totalGradeBox').style.display=m==='total'?'block':'none';}
  function ensurePage(){if(el('gradesPage'))return;const p=document.createElement('div');p.id='gradesPage';p.className='page-hidden';p.innerHTML='<header class="header grades-page-header"><div><h1>Grades</h1><p>Track coursework (70%) and culminating work (30%).</p></div><div class="grades-header-actions"><button class="secondary-button" id="gradeSettingsButton">Course Setup</button><button class="save-button" id="gradeAddButton">+ Add Grade</button></div></header><div class="grade-filters"><select id="gradeSubjectFilter"><option value="">All subjects</option></select></div><div id="gradeSubjects" class="grade-subjects"></div>';document.querySelector('.main')?.appendChild(p);el('gradeAddButton').onclick=openGradeModal;el('gradeSettingsButton').onclick=openCourseSettings;el('gradeSubjectFilter').onchange=renderGrades;}
  function ensureModal(){if(el('gradeModal'))return;const w=document.createElement('div');w.className='modal-overlay';w.id='gradeModal';w.innerHTML='<div class="modal grade-modal wide-modal"><div class="modal-header"><h2>Add Grade</h2><button class="close-button" id="gradeClose">×</button></div><div class="form-group"><label for="gradeTask">Link to schoolwork <small>(optional)</small></label><select id="gradeTask"><option value="">New / not linked to schoolwork</option></select><small class="field-hint">Choose an Assignment, Quiz, Test, Exam, Lab, or other school task already in your planner.</small></div><div class="form-group"><label for="gradeName">Name</label><input id="gradeName" placeholder="e.g. Unit 2 Test"></div><div class="form-row"><div class="form-group"><label for="gradeSubject">Subject</label><select id="gradeSubject"></select></div><div class="form-group"><label for="gradeType">Type</label><select id="gradeType"><option>Assignment</option><option>Quiz</option><option>Test</option><option>Lab</option><option>Exam</option><option>Other</option></select></div></div><div class="form-group"><label for="gradePeriod">Portion</label><select id="gradePeriod"><option value="coursework">Coursework — 70%</option><option value="culminating">Culminating — 30%</option></select></div><div class="form-row"><div class="form-group"><label for="gradeItemWeight">Weight within portion <span class="field-hint">optional</span></label><div class="percentage-input"><input id="gradeItemWeight" type="number" min="0" max="100" step="0.1"><span>%</span></div></div><div class="form-group"><label for="gradeNotes">Notes <span class="field-hint">optional</span></label><input id="gradeNotes" placeholder="Unit, teacher notes, etc."></div></div><div class="grade-entry-mode"><label><input type="radio" name="gradeMode" value="categories" checked> Category breakdown</label><label><input type="radio" name="gradeMode" value="total"> One total mark</label></div><div id="categoryGradeBox"></div><div id="totalGradeBox" style="display:none"></div><div class="modal-actions"><button class="cancel-button" id="gradeCancel">Cancel</button><button class="save-button" id="gradeSave">Add Grade</button></div></div>';document.body.appendChild(w);el('gradeClose').onclick=closeGradeModal;el('gradeCancel').onclick=closeGradeModal;el('gradeSave').onclick=createGrade;el('gradeTask').onchange=linkTask;w.addEventListener('click',e=>{if(e.target===w)closeGradeModal();});w.querySelectorAll('input[name="gradeMode"]').forEach(x=>x.onchange=renderGradeInputMode);}
  function ensureCourseModal(){if(el('courseSettingsModal'))return;const w=document.createElement('div');w.className='modal-overlay';w.id='courseSettingsModal';w.innerHTML=`<div class="modal wide-modal"><div class="modal-header"><h2>Course Grade Setup</h2><button class="close-button" id="courseClose">×</button></div><p>Coursework is 70% and culminating work is 30%. Set the four achievement-category weights.</p><div class="form-group"><label for="courseSubject">Subject</label><select id="courseSubject"></select></div><div class="category-settings-grid">${CATEGORIES.map(c=>`<div class="category-setting"><label>${c}</label><div class="percentage-input"><input id="catWeight${c}" type="number" min="0" max="100" step="0.1"><span>%</span></div></div>`).join('')}</div><div class="course-total">Category total: <strong id="categoryWeightTotal">100%</strong></div><div class="modal-actions"><button class="cancel-button" id="courseCancel">Cancel</button><button class="save-button" id="courseSave">Save Setup</button></div></div>`;document.body.appendChild(w);el('courseClose').onclick=closeCourseSettings;el('courseCancel').onclick=closeCourseSettings;el('courseSave').onclick=saveCourseSettings;el('courseSubject').onchange=loadCourseSettings;CATEGORIES.forEach(c=>el('catWeight'+c).oninput=updateCategoryTotal);}
  function openGradeModal(){ensureData();ensureModal();populateSubjects('gradeSubject',false);populateTaskLinks();renderCategoryInputs();renderTotalInput();el('gradeTask').value='';el('gradeName').value='';el('gradeSubject').value='';el('gradePeriod').value='coursework';el('gradeItemWeight').value='';el('gradeNotes').value='';document.querySelector('input[name="gradeMode"][value="categories"]').checked=true;renderGradeInputMode();el('gradeModal').classList.add('open');el('gradeName').focus();}
  function closeGradeModal(){el('gradeModal')?.classList.remove('open');}
  function createGrade(){ensureData();const name=el('gradeName').value.trim(),subject=el('gradeSubject').value,type=el('gradeType').value,portion=el('gradePeriod').value,weight=el('gradeItemWeight').value===''?null:Number(el('gradeItemWeight').value),taskId=el('gradeTask').value||null;if(!name)return alert('Please enter a grade name.');if(!subject)return alert('Please choose a subject.');if(weight!==null&&(!Number.isFinite(weight)||weight<0||weight>100))return alert('Weight must be between 0 and 100.');const mode=document.querySelector('input[name="gradeMode"]:checked')?.value||'categories';let categories=[];if(mode==='categories'){for(const c of CATEGORIES){const f=el('categoryGradeBox').querySelector(`.category-format[data-category="${c}"]`)?.value;const raw=f==='level'?el('categoryGradeBox').querySelector(`.category-level[data-category="${c}"]`)?.value:el('categoryGradeBox').querySelector(`.category-points[data-category="${c}"]`)?.value.trim();if(raw){const parsed=readMark(f,raw);if(!parsed)return alert(`Enter a valid ${c} mark.`);categories.push({category:c,...parsed});}}if(!categories.length)return alert('Enter at least one category mark.');}else{const parsed=readMark(el('gradeTotalFormat').value,el('gradeTotalValue').value.trim());if(!parsed)return alert('Enter a valid mark such as 17/20 or 3+.');categories=[{category:'Overall',...parsed}];}plannerData.gradeAssessments.push({id:Date.now(),taskId,name,subject,type,portion,weight,notes:el('gradeNotes').value.trim(),categories,createdAt:new Date().toISOString()});savePlannerData();closeGradeModal();renderGrades();}
  function calcCategory(rows){if(!rows.length)return null;const points=rows.filter(x=>x.kind==='points');if(points.length===rows.length){const e=points.reduce((a,x)=>a+x.earned,0),p=points.reduce((a,x)=>a+x.possible,0);return p?e/p*100:null;}return rows.reduce((a,x)=>a+x.percent,0)/rows.length;}
  function courseSettings(s){return plannerData.gradeSettings?.[s]||{knowledge:25,communication:25,thinking:25,application:25};}
  function calcCourse(s){const cfg=courseSettings(s),a=plannerData.gradeAssessments.filter(x=>x.subject===s),cw=a.filter(x=>x.portion==='coursework'),cu=a.filter(x=>x.portion==='culminating'),cats={};CATEGORIES.forEach(c=>cats[c]=[]);cw.forEach(x=>x.categories.forEach(r=>{if(cats[r.category])cats[r.category].push(r);}));let total=0,used=0;CATEGORIES.forEach(c=>{const avg=calcCategory(cats[c]),w=Number(cfg[c.toLowerCase()]||0);if(avg!=null&&w>0){total+=avg*w;used+=w;}});const coursework=used?total/used:null;let ct=0,cwgt=0;cu.forEach(x=>{const avg=calcCategory(x.categories);if(avg!=null){const w=x.weight>0?Number(x.weight):1;ct+=avg*w;cwgt+=w;}});const culminating=cwgt?ct/cwgt:null;const projected=coursework!=null&&culminating!=null?coursework*.7+culminating*.3:coursework!=null?coursework*.7:culminating!=null?culminating*.3:null;return{cfg,cw,cu,cats,coursework,culminating,projected};}
  function renderGrades(){ensureData();populateSubjects('gradeSubjectFilter',true);const filter=el('gradeSubjectFilter')?.value||'',list=el('gradeSubjects');if(!list)return;list.innerHTML='';activeSubjects().filter(s=>!filter||s.name===filter).forEach(s=>{const d=calcCourse(s.name),sec=document.createElement('section');sec.className='grade-subject';sec.innerHTML=`<div class="grade-subject-head"><div class="grade-subject-title"><span class="grade-subject-icon">${s.emoji||'📚'}</span><div><h2>${s.name}</h2><small>${d.cw.length} coursework • ${d.cu.length} culminating</small></div></div><strong class="grade-average">${d.projected==null?'—':d.projected.toFixed(1)+'%'}</strong></div><div class="grade-breakdown-heading"><strong>Coursework — 70%</strong><span>${d.coursework==null?'—':d.coursework.toFixed(1)+'%'}</span></div><div class="grade-category-grid">${CATEGORIES.map(c=>{const a=calcCategory(d.cats[c]);return `<div class="grade-category"><strong>${c}</strong><small>${Number(d.cfg[c.toLowerCase()]||0)}% of coursework</small><span>${a==null?'—':a.toFixed(1)+'%'}</span></div>`;}).join('')}</div><div class="grade-breakdown-heading culminating"><strong>Culminating — 30%</strong><span>${d.culminating==null?'—':d.culminating.toFixed(1)+'%'}</span></div><div class="grade-assessment-list"></div>`;const box=sec.querySelector('.grade-assessment-list');[...d.cw,...d.cu].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).forEach(a=>{const linked=(plannerData.tasks||[]).find(t=>String(t.id)===String(a.taskId));const r=document.createElement('div');r.className='grade-entry';r.innerHTML='<div><strong></strong><small></small></div><span></span>';r.querySelector('strong').textContent=a.name;r.querySelector('small').textContent=`${a.type||'Grade'} • ${a.portion==='culminating'?'Culminating':'Coursework'}${linked?' • 🔗 '+linked.name:''} • ${a.categories.map(x=>x.category+': '+x.display).join(' · ')}`;r.querySelector('span').textContent=a.categories.length===1?a.categories[0].display:'Breakdown';box.appendChild(r);});list.appendChild(sec);});}
  function openCourseSettings(){ensureData();ensureCourseModal();const s=el('courseSubject');s.innerHTML='<option value="">Choose a subject</option>';activeSubjects().forEach(x=>{const o=document.createElement('option');o.value=x.name;o.textContent=`${x.emoji||'📚'} ${x.name}`;s.appendChild(o);});s.value='';loadCourseSettings();el('courseSettingsModal').classList.add('open');}
  function closeCourseSettings(){el('courseSettingsModal')?.classList.remove('open');}
  function loadCourseSettings(){const s=el('courseSubject')?.value;if(!s)return;const c=courseSettings(s);CATEGORIES.forEach(x=>el('catWeight'+x).value=Number(c[x.toLowerCase()]||0));updateCategoryTotal();}
  function updateCategoryTotal(){let t=0;CATEGORIES.forEach(c=>t+=Number(el('catWeight'+c)?.value||0));if(el('categoryWeightTotal'))el('categoryWeightTotal').textContent=t.toFixed(1)+'%';}
  function saveCourseSettings(){const s=el('courseSubject').value;if(!s)return alert('Choose a subject.');let t=0,c={};CATEGORIES.forEach(x=>{const v=Number(el('catWeight'+x).value||0);if(!Number.isFinite(v)||v<0||v>100)throw new Error('invalid');c[x.toLowerCase()]=v;t+=v;});if(Math.abs(t-100)>0.01)return alert('The four category weights must total 100%.');plannerData.gradeSettings[s]={...plannerData.gradeSettings[s],...c};savePlannerData();closeCourseSettings();renderGrades();}
  function styles(){if(el('gradesStyles'))return;const s=document.createElement('style');s.id='gradesStyles';s.textContent='.grades-page-header{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;margin-bottom:24px}.grades-header-actions{display:flex;gap:10px}.grade-subjects{display:grid;gap:18px}.grade-subject{border:1px solid var(--border-color,#e6e1da);border-radius:18px;padding:20px;background:var(--card-bg,#fff)}.grade-subject-head{display:flex;justify-content:space-between;align-items:center}.grade-subject-title{display:flex;gap:12px;align-items:center}.grade-subject-title h2{margin:0}.grade-subject-title small,.grade-category small,.grade-entry small,.field-hint{color:var(--muted-text,#777)}.grade-subject-icon{font-size:26px}.grade-average{font-size:24px}.grade-breakdown-heading{display:flex;justify-content:space-between;margin:18px 0 10px}.grade-category-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.grade-category{border:1px solid var(--border-color,#e6e1da);border-radius:12px;padding:12px}.grade-category strong,.grade-category small,.grade-category span{display:block}.grade-category span{font-size:18px;font-weight:700;margin-top:5px}.grade-entry{display:grid;grid-template-columns:1fr auto;gap:15px;padding:12px 0;border-top:1px solid var(--border-color,#e6e1da)}.grade-entry strong,.grade-entry small{display:block}.grade-entry small{font-size:12px;margin-top:3px}.wide-modal{max-width:760px;width:calc(100% - 32px)}.category-grade-row{display:grid;grid-template-columns:1fr 150px 180px;gap:10px;align-items:center;padding:10px 0;border-top:1px solid var(--border-color,#e6e1da)}.category-name strong,.category-name small{display:block}.grade-entry-mode{display:flex;gap:20px;margin:16px 0}.category-settings-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.course-total{display:flex;justify-content:space-between;margin:18px 0;font-weight:600}.percentage-input{display:flex;align-items:center}.percentage-input input{width:100%}.percentage-input span{margin-left:-28px}.total-grade-fields{display:grid;grid-template-columns:1fr 180px;gap:12px}@media(max-width:700px){.grades-page-header,.grades-header-actions{flex-direction:column}.grade-category-grid,.category-settings-grid,.category-grade-row,.total-grade-fields{grid-template-columns:1fr}}';document.head.appendChild(s);}
  function install(){ensureData();ensurePage();ensureModal();styles();}
  window.renderGrades=renderGrades;window.openGradeModal=openGradeModal;window.closeGradeModal=closeGradeModal;window.openCourseSettings=openCourseSettings;window.closeCourseSettings=closeCourseSettings;install();document.addEventListener('DOMContentLoaded',install);window.addEventListener('load',install);
})();