// Roadmap systems foundation: Focus, Habits, Goals, Companion, Profile, Friends, Integrations, Smart Planning.
(function(){
  const D=()=>window.plannerData||(typeof plannerData!=='undefined'?plannerData:{});
  const save=()=>typeof savePlannerData==='function'?savePlannerData():localStorage.setItem('plannerData',JSON.stringify(D()));
  const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const ensure=(k,f)=>{const d=D();if(!Array.isArray(d[k]))d[k]=f?f():[];return d[k];};
  const page=(id,title,sub,body)=>{if(document.getElementById(id))return;const p=document.createElement('div');p.id=id;p.className='page-hidden roadmap-system-page';p.innerHTML=`<header class="header"><div><h1>${title}</h1><p>${sub}</p></div></header>${body}`;document.querySelector('.main')?.appendChild(p);};
  const navItem=(parent,id,label,icon)=>{if(document.querySelector(`[data-page="${id}"]`))return;const a=document.createElement('a');a.href='#'+id;a.className='nav-item';a.dataset.page=id;a.dataset.roadmapNav=id;a.textContent=icon+' '+label;a.onclick=()=>{showPage(id);return false;};parent.appendChild(a);};
  function buildNav(){const sections=document.querySelectorAll('.sidebar .nav-section');const school=sections[1],last=sections[sections.length-1];if(school)navItem(school,'study','Study','🧠');if(last){navItem(last,'focus','Focus','⏱️');navItem(last,'habits','Habits','🌱');navItem(last,'goals','Goals','🎯');navItem(last,'companion','Companion','🐾');navItem(last,'profile','Profile','👤');navItem(last,'friends','Friends','👥');navItem(last,'integrations','Integrations','🔗');navItem(last,'smart','Smart Planning','🧠');}}
  function wireFocus(){const d=D();ensure('focusSessions');const input=document.getElementById('focusMinutes'),start=document.getElementById('focusStart');if(!start)return;start.onclick=()=>{const min=Math.max(1,Number(input.value)||25);d.focusActive={startedAt:new Date().toISOString(),duration:min*60*1000};save();renderFocus();};}
  function renderFocus(){const d=D();const p=document.getElementById('focusPage');if(!p)return;const a=d.focusActive;const status=a?`<div class="roadmap-focus-active"><strong>Focus session active</strong><span>${a.duration/60000} minutes planned</span><button class="secondary-button" id="focusFinish">Finish session</button><button class="secondary-button" id="focusCancel">Cancel</button></div>`:`<div class="roadmap-focus-start"><label>Session length <input id="focusMinutes" type="number" min="1" max="240" value="25"></label><button class="save-button" id="focusStart">Start focus session</button></div>`;p.querySelector('#focusState').innerHTML=status;wireFocus();const f=document.getElementById('focusFinish'),c=document.getElementById('focusCancel');if(f)f.onclick=()=>{const now=new Date().toISOString();d.focusSessions.push({startedAt:a.startedAt,endedAt:now,duration:a.duration});delete d.focusActive;save();renderFocus();};if(c)c.onclick=()=>{delete d.focusActive;save();renderFocus();};}
  function renderHabits(){const d=D(),list=ensure('habits');const p=document.getElementById('habitsPage');if(!p)return;p.querySelector('#habitList').innerHTML=list.map((h,i)=>`<article class="roadmap-list-item"><span>${esc(h.emoji||'🌱')}</span><div><strong>${esc(h.name)}</strong><small>${esc(h.goal||'Daily habit')}</small></div><button class="secondary-button" data-habit="${i}">${h.lastDone===new Date().toISOString().slice(0,10)?'Done':'Complete today'}</button></article>`).join('')||'<div class="roadmap-empty">No habits yet.</div>';p.querySelectorAll('[data-habit]').forEach(b=>b.onclick=()=>{list[Number(b.dataset.habit)].lastDone=new Date().toISOString().slice(0,10);save();renderHabits();});}
  function renderGoals(){const d=D(),list=ensure('goals');const p=document.getElementById('goalsPage');if(!p)return;p.querySelector('#goalList').innerHTML=list.map((g,i)=>`<article class="roadmap-list-item"><span>🎯</span><div><strong>${esc(g.name)}</strong><small>${esc(g.description||'Personal goal')}</small></div><progress max="100" value="${Number(g.progress)||0}"></progress><button class="secondary-button" data-goal="${i}">+10%</button></article>`).join('')||'<div class="roadmap-empty">No goals yet.</div>';p.querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>{const g=list[Number(b.dataset.goal)];g.progress=Math.min(100,(Number(g.progress)||0)+10);save();renderGoals();});}
  function renderCompanion(){const d=D();d.companion=d.companion||{name:'Luna',pet:'🐰',mood:75};const p=document.getElementById('companionPage');if(!p)return;p.querySelector('#companionCard').innerHTML=`<div class="companion-avatar">${esc(d.companion.pet)}</div><h2>${esc(d.companion.name)}</h2><p>Mood ${Math.round(d.companion.mood)}%</p><div class="roadmap-actions"><button class="save-button" id="petCare">Give attention</button><button class="secondary-button" id="petRest">Let ${esc(d.companion.name)} rest</button></div>`;document.getElementById('petCare').onclick=()=>{d.companion.mood=Math.min(100,d.companion.mood+5);save();renderCompanion();};document.getElementById('petRest').onclick=()=>{d.companion.mood=Math.min(100,d.companion.mood+2);save();renderCompanion();};}
  function renderProfile(){const d=D(),p=document.getElementById('profilePage');if(!p)return;const profile=d.profile||{};p.querySelector('#profileCard').innerHTML=`<div class="profile-avatar">${esc(profile.avatar||'🌿')}</div><h2>${esc(profile.name||'Your profile')}</h2><p>Personal planner profile</p><label>Display name <input id="profileName" value="${esc(profile.name||'')}"></label><label>Avatar <input id="profileAvatar" value="${esc(profile.avatar||'🌿')}"></label><button class="save-button" id="profileSave">Save profile</button>`;document.getElementById('profileSave').onclick=()=>{d.profile={name:document.getElementById('profileName').value.trim(),avatar:document.getElementById('profileAvatar').value.trim()||'🌿'};save();renderProfile();};}
  function renderFriends(){const d=D(),list=ensure('friends');const p=document.getElementById('friendsPage');if(!p)return;p.querySelector('#friendsList').innerHTML=list.map(f=>`<article class="roadmap-list-item"><span>👤</span><div><strong>${esc(f.name)}</strong><small>${esc(f.status||'Friend')}</small></div></article>`).join('')||'<div class="roadmap-empty">Friends and shared projects will appear here.</div>';}
  function renderIntegrations(){const p=document.getElementById('integrationsPage');if(!p)return;p.querySelector('#integrationList').innerHTML=['Google Calendar','School platform','Email','Music services'].map(x=>`<article class="roadmap-list-item"><span>🔗</span><div><strong>${x}</strong><small>Integration foundation — connection controls can be added later.</small></div><button class="secondary-button">Connect</button></article>`).join('');}
  function renderSmart(){const d=D(),tasks=(d.tasks||[]).filter(t=>t.status!=='Completed').sort((a,b)=>String(a.dueDate||'9999').localeCompare(String(b.dueDate||'9999')));const p=document.getElementById('smartPage');if(!p)return;p.querySelector('#smartResults').innerHTML=tasks.slice(0,8).map(t=>`<article class="roadmap-list-item"><span>🧠</span><div><strong>${esc(t.name)}</strong><small>${esc(t.subject||'')}${t.dueDate?' · Due '+esc(t.dueDate):''}</small></div></article>`).join('')||'<div class="roadmap-empty">Nothing urgent detected.</div>';}
  function buildPages(){
    page('focusPage','Focus Space','A dedicated place for focused work, timers, and session history.','<section class="card"><h2>Timer</h2><div id="focusState"></div></section><section class="card"><h2>Session history</h2><div id="focusHistory"></div></section>');
    page('habitsPage','Habits','Build routines gently and track consistency.','<section class="card"><h2>Your habits</h2><div id="habitList"></div></section>');
    page('goalsPage','Goals','Track personal and school goals without pressure.','<section class="card"><h2>Your goals</h2><div id="goalList"></div></section>');
    page('companionPage','Companion','A gentle productivity companion that never punishes rest.','<section class="card companion-card" id="companionCard"></section>');
    page('profilePage','Profile','Your planner identity and preferences.','<section class="card profile-card" id="profileCard"></section>');
    page('friendsPage','Friends','Friends, sharing, and collaborative projects.','<section class="card"><h2>Friends</h2><div id="friendsList"></div></section><section class="card"><h2>Shared projects</h2><p>Collaborative project tools are ready for the next connection layer.</p></section>');
    page('integrationsPage','Integrations','Connect calendars, school platforms, email, and music.','<section class="card"><h2>Available integrations</h2><div id="integrationList"></div></section>');
    page('smartPage','Smart Planning','Turn deadlines and available time into practical suggestions.','<section class="card"><h2>Suggested next work</h2><p>Based on unfinished tasks and due dates.</p><div id="smartResults"></div></section>');
  }
  function render(){renderFocus();renderHabits();renderGoals();renderCompanion();renderProfile();renderFriends();renderIntegrations();renderSmart();const d=D();const h=document.getElementById('focusHistory');if(h)h.innerHTML=(d.focusSessions||[]).slice(-10).reverse().map(s=>`<div class="roadmap-history-row">${new Date(s.startedAt).toLocaleString()} · ${Math.round(s.duration/60000)} min</div>`).join('')||'<div class="roadmap-empty">No sessions yet.</div>';}
  function init(){buildNav();buildPages();render();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
  window.addEventListener('planner-data-changed',render);
})();