// Roadmap systems foundation: Focus, Habits, Goals, Companion, Profile, Friends, Integrations, Smart Planning, Study Map.
(function(){
  const D=()=>window.plannerData||(typeof plannerData!=='undefined'?plannerData:{});
  const save=()=>typeof savePlannerData==='function'?savePlannerData():localStorage.setItem('plannerData',JSON.stringify(D()));
  const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const ensure=(k,f)=>{const d=D();if(!Array.isArray(d[k]))d[k]=f?f():[];return d[k];};
  const today=()=>new Date().toISOString().slice(0,10);
  const dayNames=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
  const page=(id,title,sub,body)=>{if(document.getElementById(id))return;const p=document.createElement('div');p.id=id;p.className='page-hidden roadmap-system-page';p.innerHTML=`<header class="header"><div><h1>${title}</h1><p>${sub}</p></div></header>${body}`;document.querySelector('.main')?.appendChild(p);};
  const navItem=(parent,id,label,icon)=>{if(document.querySelector(`[data-page="${id}"]`))return;const a=document.createElement('a');a.href='#'+id;a.className='nav-item';a.dataset.page=id;a.dataset.roadmapNav=id;a.textContent=icon+' '+label;a.onclick=()=>{showPage(id);return false;};parent.appendChild(a);};
  function buildNav(){const sections=document.querySelectorAll('.sidebar .nav-section');const last=sections[sections.length-1];if(last){navItem(last,'focus','Focus','⏱️');navItem(last,'habits','Habits','🌱');navItem(last,'goals','Goals','🎯');navItem(last,'profile','Profile','👤');navItem(last,'friends','Friends','👥');navItem(last,'integrations','Integrations','🔗');navItem(last,'smart','Smart Planning','🧠');navItem(last,'study-map','Study Map','🗺️');}}
  function wireFocus(){const d=D();ensure('focusSessions');const input=document.getElementById('focusMinutes'),start=document.getElementById('focusStart');if(!start)return;start.onclick=()=>{const min=Math.max(1,Number(input.value)||25);d.focusActive={startedAt:new Date().toISOString(),duration:min*60*1000};save();renderFocus();};}
  function renderFocus(){const d=D();const p=document.getElementById('focusPage');if(!p)return;const a=d.focusActive;const status=a?`<div class="roadmap-focus-active"><strong>Focus session active</strong><span>${a.duration/60000} minutes planned</span><button class="secondary-button" id="focusFinish">Finish session</button><button class="secondary-button" id="focusCancel">Cancel</button></div>`:`<div class="roadmap-focus-start"><label>Session length <input id="focusMinutes" type="number" min="1" max="240" value="25"></label><button class="save-button" id="focusStart">Start focus session</button></div>`;p.querySelector('#focusState').innerHTML=status;wireFocus();const f=document.getElementById('focusFinish'),c=document.getElementById('focusCancel');if(f)f.onclick=()=>{const now=new Date().toISOString();d.focusSessions.push({startedAt:a.startedAt,endedAt:now,duration:a.duration});delete d.focusActive;save();renderFocus();};if(c)c.onclick=()=>{delete d.focusActive;save();renderFocus();};}
  function habitFrequencyText(h){const f=h.frequency||'daily';if(f==='weekly')return `Weekly · ${Number(h.target||1)} time${Number(h.target||1)===1?'':'s'}`;if(f==='custom')return (h.days||[]).map(x=>dayNames[x]).join(', ')||'Choose days';return 'Daily';}
  function habitScheduledToday(h){if(h.frequency==='weekly')return true;if(h.frequency==='custom')return (h.days||[]).map(Number).includes(new Date().getDay());return true;}
  function habitDoneToday(h){return Array.isArray(h.completedDates)&&h.completedDates.includes(today());}
  function habitStreak(h){const dates=[...(h.completedDates||[])].filter(Boolean).sort().reverse();let streak=0,d=new Date();if(!habitDoneToday(h))d.setDate(d.getDate()-1);for(const wanted of dates){const ds=d.toISOString().slice(0,10);if(wanted!==ds)break;streak++;d.setDate(d.getDate()-1);}return streak;}
  function habitRate(h){const dates=new Set(h.completedDates||[]);let possible=0,done=0;for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()-i);if(h.frequency==='custom'&&!((h.days||[]).map(Number).includes(d.getDay())))continue;possible++;if(dates.has(d.toISOString().slice(0,10)))done++;}return possible?Math.round(done/possible*100):0;}
  function openHabitModal(index){
    const list=ensure('habits'), old=index==null?null:list[index];
    document.getElementById('habitModal')?.remove();
    const modal=document.createElement('div');modal.id='habitModal';modal.className='roadmap-modal-backdrop';
    const days=(old?.days||[1,2,3,4,5]).map(Number);
    modal.innerHTML=`<div class="roadmap-modal card"><div class="roadmap-modal-head"><div><h2>${old?'Edit habit':'Add habit'}</h2><p>Create a habit you can actually track.</p></div><button class="secondary-button" id="habitClose">Close</button></div><div class="habit-form-grid"><label>Name<input id="habitName" value="${esc(old?.name||'')}" placeholder="e.g. Read for 20 minutes"></label><label>Icon<input id="habitEmoji" value="${esc(old?.emoji||'🌱')}" maxlength="4"></label><label>Goal<input id="habitGoal" value="${esc(old?.goal||'')}" placeholder="Optional goal"></label><label>Frequency<select id="habitFrequency"><option value="daily" ${old?.frequency==='daily'||!old?'selected':''}>Every day</option><option value="weekly" ${old?.frequency==='weekly'?'selected':''}>Weekly target</option><option value="custom" ${old?.frequency==='custom'?'selected':''}>Specific days</option></select></label><label id="habitTargetWrap">Weekly target<input id="habitTarget" type="number" min="1" max="7" value="${Number(old?.target)||1}"></label></div><div id="habitDaysWrap" class="habit-days-wrap"><strong>Days</strong><div class="habit-day-picker">${dayNames.map((n,i)=>`<label><input type="checkbox" data-day="${i}" ${days.includes(i)?'checked':''}>${n}</label>`).join('')}</div></div><div class="roadmap-actions"><button class="save-button" id="habitSave">${old?'Save changes':'Add habit'}</button>${old?'<button class="secondary-button" id="habitDelete">Delete habit</button>':''}</div></div>`;
    document.body.appendChild(modal);
    const freq=modal.querySelector('#habitFrequency'),targetWrap=modal.querySelector('#habitTargetWrap'),daysWrap=modal.querySelector('#habitDaysWrap');
    const sync=()=>{targetWrap.style.display=freq.value==='weekly'?'flex':'none';daysWrap.style.display=freq.value==='custom'?'block':'none';};sync();freq.onchange=sync;
    modal.querySelector('#habitClose').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove();};
    modal.querySelector('#habitSave').onclick=()=>{const name=modal.querySelector('#habitName').value.trim();if(!name){modal.querySelector('#habitName').focus();return;}const h=old||{createdAt:new Date().toISOString(),completedDates:[]};h.name=name;h.emoji=modal.querySelector('#habitEmoji').value.trim()||'🌱';h.goal=modal.querySelector('#habitGoal').value.trim();h.frequency=freq.value;h.target=Math.min(7,Math.max(1,Number(modal.querySelector('#habitTarget').value)||1));h.days=[...modal.querySelectorAll('[data-day]:checked')].map(x=>Number(x.dataset.day));if(!Array.isArray(h.completedDates))h.completedDates=[];if(old)list[index]=h;else list.push(h);save();modal.remove();renderHabits();};
    if(old)modal.querySelector('#habitDelete').onclick=()=>{if(confirm(`Delete ${old.name}?`)){list.splice(index,1);save();modal.remove();renderHabits();}};
  }
  function openRoutineModal(index){
    const routines=ensure('routines'),habits=ensure('habits'),old=index==null?null:routines[index];
    document.getElementById('routineModal')?.remove();
    const modal=document.createElement('div');modal.id='routineModal';modal.className='roadmap-modal-backdrop';
    const selected=old?.habitIds||[];
    modal.innerHTML=`<div class="roadmap-modal card"><div class="roadmap-modal-head"><div><h2>${old?'Edit routine':'Build routine'}</h2><p>Put your habits into a repeatable sequence.</p></div><button class="secondary-button" id="routineClose">Close</button></div><div class="habit-form-grid"><label>Routine name<input id="routineName" value="${esc(old?.name||'')}" placeholder="e.g. Morning routine"></label><label>Time<input id="routineTime" type="time" value="${esc(old?.time||'')}"></label><label>Days<select id="routineFrequency"><option value="daily" ${old?.frequency!=='custom'?'selected':''}>Every day</option><option value="custom" ${old?.frequency==='custom'?'selected':''}>Specific days</option></select></label></div><div id="routineDays" class="habit-days-wrap"><strong>Days</strong><div class="habit-day-picker">${dayNames.map((n,i)=>`<label><input type="checkbox" data-rday="${i}" ${(old?.days||[1,2,3,4,5]).map(Number).includes(i)?'checked':''}>${n}</label>`).join('')}</div></div><div class="routine-builder"><div class="routine-builder-head"><h3>Routine steps</h3><span>${habits.length} habits available</span></div><div id="routineSteps">${habits.length?habits.map((h,i)=>`<label class="routine-step"><input type="checkbox" data-rhabit="${i}" ${selected.includes(i)?'checked':''}><span>${esc(h.emoji||'🌱')}</span><div><strong>${esc(h.name)}</strong><small>${esc(h.goal||habitFrequencyText(h))}</small></div></label>`).join(''):'<div class="roadmap-empty">Add some habits first, then they will appear here.</div>'}</div></div><div class="roadmap-actions"><button class="save-button" id="routineSave">${old?'Save routine':'Create routine'}</button>${old?'<button class="secondary-button" id="routineDelete">Delete routine</button>':''}</div></div>`;
    document.body.appendChild(modal);const freq=modal.querySelector('#routineFrequency'),days=modal.querySelector('#routineDays');const sync=()=>days.style.display=freq.value==='custom'?'block':'none';sync();freq.onchange=sync;
    modal.querySelector('#routineClose').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove();};
    modal.querySelector('#routineSave').onclick=()=>{const name=modal.querySelector('#routineName').value.trim();if(!name){modal.querySelector('#routineName').focus();return;}const r=old||{createdAt:new Date().toISOString(),completedDates:[]};r.name=name;r.time=modal.querySelector('#routineTime').value;r.frequency=freq.value;r.days=[...modal.querySelectorAll('[data-rday]:checked')].map(x=>Number(x.dataset.rday));r.habitIds=[...modal.querySelectorAll('[data-rhabit]:checked')].map(x=>Number(x.dataset.rhabit));if(old)routines[index]=r;else routines.push(r);save();modal.remove();renderHabits();};
    if(old)modal.querySelector('#routineDelete').onclick=()=>{if(confirm(`Delete ${old.name}?`)){routines.splice(index,1);save();modal.remove();renderHabits();}};
  }
  function completeHabit(i){const list=ensure('habits'),h=list[i];if(!h)return;h.completedDates=Array.isArray(h.completedDates)?h.completedDates:[];const t=today(),pos=h.completedDates.indexOf(t);if(pos>=0)h.completedDates.splice(pos,1);else h.completedDates.push(t);h.lastDone=habitDoneToday(h)?t:'';save();renderHabits();}
  function completeRoutine(i){const list=ensure('routines'),r=list[i];if(!r)return;r.completedDates=Array.isArray(r.completedDates)?r.completedDates:[];const t=today(),pos=r.completedDates.indexOf(t);if(pos>=0)r.completedDates.splice(pos,1);else r.completedDates.push(t);save();renderHabits();}
  function renderHabits(){
    const d=D(),list=ensure('habits'),routines=ensure('routines');const p=document.getElementById('habitsPage');if(!p)return;const scheduled=list.filter(habitScheduledToday);const done=scheduled.filter(habitDoneToday).length;const streaks=list.map(habitStreak);const best=Math.max(0,...streaks);const rate=scheduled.length?Math.round(done/scheduled.length*100):0;
    p.querySelector('#habitStats').innerHTML=`<div class="habit-stat"><strong>${done}/${scheduled.length}</strong><span>Today</span></div><div class="habit-stat"><strong>${rate}%</strong><span>7-day rate</span></div><div class="habit-stat"><strong>${best}</strong><span>Best current streak</span></div><div class="habit-stat"><strong>${list.length}</strong><span>Active habits</span></div>`;
    p.querySelector('#habitList').innerHTML=list.map((h,i)=>`<article class="habit-card ${habitDoneToday(h)?'habit-done':''}"><div class="habit-card-icon">${esc(h.emoji||'🌱')}</div><div class="habit-card-main"><strong>${esc(h.name)}</strong><small>${esc(h.goal||'No goal')} · ${habitFrequencyText(h)}</small><div class="habit-meta"><span>🔥 ${habitStreak(h)} day streak</span><span>${habitRate(h)}% this week</span></div></div><button class="secondary-button" data-habit="${i}">${habitDoneToday(h)?'Undo today':'Complete'}</button><button class="icon-button" data-edit-habit="${i}" title="Edit">✏️</button></article>`).join('')||'<div class="roadmap-empty">No habits yet. Add your first one above.</div>';
    p.querySelector('#routineList').innerHTML=routines.map((r,i)=>{const ids=r.habitIds||[];const rd=Array.isArray(r.completedDates)&&r.completedDates.includes(today());return `<article class="routine-card ${rd?'habit-done':''}"><div class="routine-card-head"><div><h3>🔁 ${esc(r.name)}</h3><small>${r.frequency==='custom'?(r.days||[]).map(x=>dayNames[x]).join(', '):'Every day'}${r.time?' · '+esc(r.time):''}</small></div><div class="roadmap-actions"><button class="secondary-button" data-routine="${i}">${rd?'Undo today':'Complete routine'}</button><button class="icon-button" data-edit-routine="${i}" title="Edit">✏️</button></div></div><div class="routine-steps">${ids.length?ids.map((id,n)=>{const h=list[id];return h?`<span>${n+1}. ${esc(h.emoji||'🌱')} ${esc(h.name)}</span>`:''}).join(''): '<span>No habits assigned yet.</span>'}</div></article>`}).join('')||'<div class="roadmap-empty">No routines yet. Build one from your habits.</div>';
    p.querySelector('#habitList').querySelectorAll('[data-habit]').forEach(b=>b.onclick=()=>completeHabit(Number(b.dataset.habit)));p.querySelectorAll('[data-edit-habit]').forEach(b=>b.onclick=()=>openHabitModal(Number(b.dataset.editHabit)));p.querySelectorAll('[data-routine]').forEach(b=>b.onclick=()=>completeRoutine(Number(b.dataset.routine)));p.querySelectorAll('[data-edit-routine]').forEach(b=>b.onclick=()=>openRoutineModal(Number(b.dataset.editRoutine)));
    document.getElementById('addHabitBtn').onclick=()=>openHabitModal();document.getElementById('addRoutineBtn').onclick=()=>openRoutineModal();
  }
  function renderGoals(){const d=D(),list=ensure('goals');const p=document.getElementById('goalsPage');if(!p)return;p.querySelector('#goalList').innerHTML=list.map((g,i)=>`<article class="roadmap-list-item"><span>🎯</span><div><strong>${esc(g.name)}</strong><small>${esc(g.description||'Personal goal')}</small></div><progress max="100" value="${Number(g.progress)||0}"></progress><button class="secondary-button" data-goal="${i}">+10%</button></article>`).join('')||'<div class="roadmap-empty">No goals yet.</div>';p.querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>{const g=list[Number(b.dataset.goal)];g.progress=Math.min(100,(Number(g.progress)||0)+10);save();renderGoals();});}
  function renderCompanion(){const d=D();d.companion=d.companion||{name:'Luna',pet:'🐰',mood:75};const p=document.getElementById('companionPage');if(!p)return;p.querySelector('#companionCard').innerHTML=`<div class="companion-avatar">${esc(d.companion.pet)}</div><h2>${esc(d.companion.name)}</h2><p>Mood ${Math.round(d.companion.mood)}%</p><div class="roadmap-actions"><button class="save-button" id="petCare">Give attention</button><button class="secondary-button" id="petRest">Let ${esc(d.companion.name)} rest</button></div>`;document.getElementById('petCare').onclick=()=>{d.companion.mood=Math.min(100,d.companion.mood+5);save();renderCompanion();};document.getElementById('petRest').onclick=()=>{d.companion.mood=Math.min(100,d.companion.mood+2);save();renderCompanion();};}
  function renderProfile(){const d=D(),p=document.getElementById('profilePage');if(!p)return;const profile=d.profile||{};p.querySelector('#profileCard').innerHTML=`<div class="profile-avatar">${esc(profile.avatar||'🌿')}</div><h2>${esc(profile.name||'Your profile')}</h2><p>Personal planner profile</p><label>Display name <input id="profileName" value="${esc(profile.name||'')}"></label><label>Avatar <input id="profileAvatar" value="${esc(profile.avatar||'🌿')}"></label><button class="save-button" id="profileSave">Save profile</button>`;document.getElementById('profileSave').onclick=()=>{d.profile={name:document.getElementById('profileName').value.trim(),avatar:document.getElementById('profileAvatar').value.trim()||'🌿'};save();renderProfile();};}
  function renderFriends(){const d=D(),list=ensure('friends');const p=document.getElementById('friendsPage');if(!p)return;p.querySelector('#friendsList').innerHTML=list.map(f=>`<article class="roadmap-list-item"><span>👤</span><div><strong>${esc(f.name)}</strong><small>${esc(f.status||'Friend')}</small></div></article>`).join('')||'<div class="roadmap-empty">Friends and shared projects will appear here.</div>';}
  function renderIntegrations(){const p=document.getElementById('integrationsPage');if(!p)return;p.querySelector('#integrationList').innerHTML=['Google Calendar','School platform','Email','Music services'].map(x=>`<article class="roadmap-list-item"><span>🔗</span><div><strong>${x}</strong><small>Integration foundation — connection controls can be added later.</small></div><button class="secondary-button">Connect</button></article>`).join('');}
  function renderSmart(){const d=D(),tasks=(d.tasks||[]).filter(t=>t.status!=='Completed').sort((a,b)=>String(a.dueDate||'9999').localeCompare(String(b.dueDate||'9999')));const p=document.getElementById('smartPage');if(!p)return;p.querySelector('#smartResults').innerHTML=tasks.slice(0,8).map(t=>`<article class="roadmap-list-item"><span>🧠</span><div><strong>${esc(t.name)}</strong><small>${esc(t.subject||'')}${t.dueDate?' · Due '+esc(t.dueDate):''}</small></div></article>`).join('')||'<div class="roadmap-empty">Nothing urgent detected.</div>';}
  function renderStudyMap(){
    const d=D();
    const p=document.getElementById('study-mapPage');
    if(!p)return;
    const subjects=Array.isArray(d.settings?.subjects)?d.settings.subjects.filter(s=>s&&s.active!==false):[];
    const tasks=Array.isArray(d.tasks)?d.tasks:[];
    const sets=Array.isArray(d.studySets)?d.studySets:[];
    const cards=subjects.map(s=>{
      const roadmap=Array.isArray(s.roadmap)?s.roadmap:[];
      const subjectTasks=tasks.filter(t=>String(t.subject||'').toLowerCase()===String(s.name||'').toLowerCase());
      const subjectSets=sets.filter(x=>String(x.subject||'').toLowerCase()===String(s.name||'').toLowerCase());
      const lessons=roadmap.reduce((n,u)=>n+(Array.isArray(u.lessons)?u.lessons.length:0),0);
      const done=roadmap.reduce((n,u)=>n+(Array.isArray(u.lessons)?u.lessons.filter(l=>l.completed||l.status==='Completed').length:0),0);
      return `<article class="study-map-subject"><div class="study-map-subject-head"><div class="study-map-icon">${esc(s.emoji||'📚')}</div><div><h2>${esc(s.name)}</h2><p>${roadmap.length} unit${roadmap.length===1?'':'s'} · ${done}/${lessons} lessons · ${subjectSets.length} study set${subjectSets.length===1?'':'s'}</p></div><button class="small-button" data-study-map-subject="${encodeURIComponent(s.name)}">Open subject</button></div><div class="study-map-path">${roadmap.length?roadmap.map((u,i)=>{const ls=Array.isArray(u.lessons)?u.lessons:[];const ld=ls.filter(l=>l.completed||l.status==='Completed').length;const assigned=subjectTasks.filter(t=>String(t.roadmapUnitId)===String(u.id)).length;return `<div class="study-map-unit"><span class="study-map-node">${ld===ls.length&&ls.length?'✓':i+1}</span><div><strong>${esc(u.name||'Unit '+(i+1))}</strong><small>${ld}/${ls.length} lessons${assigned?' · '+assigned+' linked work':''}</small></div></div>`;}).join('<span class="study-map-connector"></span>'):`<div class="study-map-empty-path">Add units and lessons on the subject roadmap to build this path.</div>`}</div></article>`;
    }).join('');
    p.querySelector('#studyMapContent').innerHTML=cards||'<div class="study-map-empty">Add an active subject to start building your study map.</div>';
    p.querySelectorAll('[data-study-map-subject]').forEach(b=>b.onclick=()=>{const name=decodeURIComponent(b.dataset.studyMapSubject);if(typeof window.openSubjectPage==='function')window.openSubjectPage(name,true);else location.hash='subject/'+encodeURIComponent(name);});
  }
  function buildPages(){
    page('focusPage','Focus Space','A dedicated place for focused work, timers, and session history.','<section class="card"><h2>Timer</h2><div id="focusState"></div></section><section class="card"><h2>Session history</h2><div id="focusHistory"></div></section>');
    page('habitsPage','Habits','Build habits, track consistency, and create routines.','<section class="card habits-toolbar"><div><div class="eyebrow">Your habits</div><h2>Small actions, repeated</h2><p>Track the things you want to do regularly without turning your planner into a punishment system.</p></div><div class="roadmap-actions"><button class="save-button" id="addHabitBtn">＋ Add habit</button><button class="secondary-button" id="addRoutineBtn">＋ Build routine</button></div></section><section class="habit-stats" id="habitStats"></section><section class="card"><div class="section-title-row"><h2>Today's habits</h2><span>Check them off as you go</span></div><div id="habitList"></div></section><section class="card"><div class="section-title-row"><h2>Routines</h2><span>Repeatable groups of habits</span></div><div id="routineList"></div></section>');
    page('goalsPage','Goals','Track personal and school goals.','<section class="card"><h2>Your goals</h2><div id="goalList"></div></section>');
    page('companionPage','Companion','A gentle productivity companion that never punishes rest.','<section class="card companion-card" id="companionCard"></section>');
    page('profilePage','Profile','Your planner identity and preferences.','<section class="card profile-card" id="profileCard"></section>');
    page('friendsPage','Friends','Friends, sharing, and collaborative projects.','<section class="card"><h2>Friends</h2><div id="friendsList"></div></section><section class="card"><h2>Shared projects</h2><p>Collaborative project tools are ready for the next connection layer.</p></section>');
    page('integrationsPage','Integrations','Connect calendars, school platforms, email, and music.','<section class="card"><h2>Available integrations</h2><div id="integrationList"></div></section>');
    page('smartPage','Smart Planning','Turn deadlines and available time into practical suggestions.','<section class="card"><h2>Suggested next work</h2><p>Based on unfinished tasks and due dates.</p><div id="smartResults"></div></section>');
    page('study-mapPage','Study Map','See each subject as a learning path from units to lessons.','<section class="card study-map-intro"><div><div class="eyebrow">Learning paths</div><h2>See where you are going</h2><p>The map connects your subject roadmaps to lessons, linked work, and study material. Your AI study helper can eventually live alongside each lesson here.</p></div></section><div id="studyMapContent" class="study-map-content"></div>');
  }
  function render(){renderFocus();renderHabits();renderGoals();renderCompanion();renderProfile();renderFriends();renderIntegrations();renderSmart();renderStudyMap();const d=D();const h=document.getElementById('focusHistory');if(h)h.innerHTML=(d.focusSessions||[]).slice(-10).reverse().map(s=>`<div class="roadmap-history-row">${new Date(s.startedAt).toLocaleString()} · ${Math.round(s.duration/60000)} min</div>`).join('')||'<div class="roadmap-empty">No sessions yet.</div>';}
  function init(){buildNav();buildPages();render();}
  window.renderRoadmapCore=init;
  window.renderStudyMap=renderStudyMap;
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
  window.addEventListener('planner-data-changed',render);
})();