// ========================================
// STUDY SYSTEM — EVIDENCE-INFORMED FOUNDATION
// ========================================
(function(){
  const METHODS=[
    {id:'retrieval',icon:'🧠',name:'Active recall',strength:'High',desc:'Recall information from memory before looking at the answer. Use questions, flashcards, or blank-page recall.',best:['Biology','Chemistry','History','English','Physics','Math']},
    {id:'spacing',icon:'📅',name:'Spaced repetition',strength:'High',desc:'Return to material across separated sessions instead of doing one large cram session.',best:['All subjects']},
    {id:'practice',icon:'✍️',name:'Practice testing',strength:'High',desc:'Answer practice questions or mini-tests, then check your answers and correct errors.',best:['Physics','Math','Chemistry','Biology','All subjects']},
    {id:'interleaving',icon:'🔀',name:'Interleaving',strength:'Moderate',desc:'Mix related topics or problem types so you have to decide which approach applies.',best:['Math','Physics','Chemistry']},
    {id:'self-explanation',icon:'💬',name:'Self-explanation',strength:'Moderate',desc:'Explain why an answer, equation, step, or idea makes sense rather than only memorizing it.',best:['Math','Physics','Chemistry','Biology']},
    {id:'feynman',icon:'🗣️',name:'Feynman technique',strength:'Useful',desc:'Explain a concept simply from memory, identify gaps, then return to the source and improve the explanation.',best:['Biology','Chemistry','Physics','History','English']},
    {id:'blurting',icon:'📝',name:'Blurting',strength:'Retrieval-based',desc:'Study briefly, close the material, then write everything you can remember. Compare, correct, and repeat.',best:['Biology','History','Chemistry','English']},
    {id:'worked',icon:'🧩',name:'Worked examples → independent problems',strength:'Useful',desc:'Study a solved example, explain each step, then solve a similar problem without looking.',best:['Math','Physics','Chemistry']},
    {id:'elaboration',icon:'🔎',name:'Elaborative questioning',strength:'Moderate',desc:'Ask why and how facts connect to other ideas you already know.',best:['Biology','Chemistry','History','English']}
  ];
  const PROFILES=[
    {keys:['math','functions','calculus','advanced functions'],methods:['worked','practice','interleaving','retrieval','spacing']},
    {keys:['physics','physic'],methods:['worked','practice','self-explanation','interleaving','retrieval','spacing']},
    {keys:['chem','chemistry'],methods:['retrieval','practice','worked','feynman','spacing','interleaving']},
    {keys:['bio','biology'],methods:['retrieval','blurting','feynman','elaboration','spacing']},
    {keys:['english','history','geography','social'],methods:['retrieval','blurting','feynman','elaboration','spacing','practice']}
  ];
  function data(){return (typeof plannerData!=='undefined'&&plannerData)||window.plannerData||{};}
  function subjects(){return (data().settings?.subjects||[]).filter(s=>s&&s.active!==false);}
  function ensureData(){if(!Array.isArray(data().studySets))data().studySets=[];if(!Array.isArray(data().studyPlans))data().studyPlans=[];}
  function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
  function subjectProfile(subject){
    const n=String(subject||'').toLowerCase();
    const hit=PROFILES.find(p=>p.keys.some(k=>n.includes(k)));
    return hit?hit.methods:['retrieval','practice','spacing','self-explanation'];
  }
  function method(id){return METHODS.find(m=>m.id===id);}
  function ensurePage(){
    let nav=document.querySelector('[data-page="study"]');
    if(!nav){
      const school=document.querySelector('.sidebar .nav-section:nth-of-type(2)');
      if(school){nav=document.createElement('a');nav.href='#study';nav.className='nav-item';nav.dataset.page='study';nav.textContent='🧠 Study';nav.onclick=()=>{showPage('study');return false;};school.appendChild(nav);}
    }
    let p=document.getElementById('studyPage');
    if(!p){p=document.createElement('div');p.id='studyPage';p.className='page-hidden';document.querySelector('.main')?.appendChild(p);}
    p.innerHTML=`<header class="header study-page-header"><div><h1>Study</h1><p>Study smarter with evidence-informed methods, subject-specific plans, and spaced review.</p></div><button class="save-button" id="studyNewSet">+ New Study Set</button></header>
    <div class="study-tabs"><button class="study-tab active" data-tab="home">Overview</button><button class="study-tab" data-tab="plans">Study plans</button><button class="study-tab" data-tab="methods">Methods</button><button class="study-tab" data-tab="sets">Study sets</button></div>
    <section id="studyTabHome" class="study-tab-panel"><div class="study-summary"><div class="study-stat"><strong id="studySetCount">0</strong><span>Study sets</span></div><div class="study-stat"><strong id="studyDueCount">0</strong><span>Due for review</span></div><div class="study-stat"><strong id="studyPlanCount">0</strong><span>Study plans</span></div></div><section class="card study-card"><div class="study-section-title"><div><h2>Today's study</h2><p id="studyTodaySubtitle">Choose a subject to see its recommended study approach.</p></div><select id="studyHomeSubject"></select></div><div id="studyTodayPlan"></div></section><section class="card study-card"><div class="study-section-title"><div><h2>How the system works</h2><p>The planner combines high-utility learning techniques with subject-specific practice.</p></div></div><div class="study-principles"><div><b>1. Learn</b><span>Understand the new material first.</span></div><div><b>2. Retrieve</b><span>Close the notes and bring it back from memory.</span></div><div><b>3. Space</b><span>Schedule another retrieval session later.</span></div><div><b>4. Apply</b><span>Use questions or problems that require the knowledge.</span></div><div><b>5. Correct</b><span>Check errors and revisit weak areas.</span></div></div></section></section>
    <section id="studyTabPlans" class="study-tab-panel hidden"><section class="card study-card"><div class="study-section-title"><div><h2>Subject study plans</h2><p>Each subject gets a different mix of methods based on the kind of learning it usually requires.</p></div><button class="secondary-button" id="generatePlans">Generate / refresh plans</button></div><div id="studyPlans"></div></section></section>
    <section id="studyTabMethods" class="study-tab-panel hidden"><section class="card study-card"><div class="study-section-title"><div><h2>Study method library</h2><p>These are tools you can combine rather than a single “perfect” study method.</p></div></div><div id="studyMethods" class="study-method-grid"></div></section></section>
    <section id="studyTabSets" class="study-tab-panel hidden"><section class="card study-card"><div class="study-section-title"><div><h2>Your study sets</h2><p>Flashcards, notes, and question banks will plug into the study plans.</p></div><select id="studySetFilter"></select></div><div id="studySets" class="study-sets"></div></section></section>`;
    p.querySelector('#studyNewSet').onclick=()=>window.openStudySetModal?.();
    p.querySelectorAll('.study-tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
    p.querySelector('#generatePlans').onclick=generatePlans;
    p.querySelector('#studyHomeSubject').onchange=renderToday;
    p.querySelector('#studySetFilter').onchange=renderSets;
    return p;
  }
  function switchTab(tab){document.querySelectorAll('.study-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.study-tab-panel').forEach(p=>p.classList.toggle('hidden',p.id!==`studyTab${tab[0].toUpperCase()+tab.slice(1)}`));if(tab==='plans')renderPlans();if(tab==='methods')renderMethods();if(tab==='sets')renderSets();}
  function renderToday(){const d=data(),select=document.getElementById('studyHomeSubject'),name=select?.value||subjects()[0]?.name||'';if(select&&!select.options.length)populateSubjects();const methods=subjectProfile(name).map(method).filter(Boolean);const box=document.getElementById('studyTodayPlan');if(!box)return;if(!name){box.innerHTML='<div class="study-empty"><h3>Add an active subject first</h3><p>Your study plans will appear here once your subjects are set up.</p></div>';return;}box.innerHTML=`<div class="study-subject-plan"><div class="study-plan-heading"><span class="study-plan-icon">${esc(subjects().find(s=>s.name===name)?.emoji||'📚')}</span><div><h3>${esc(name)}</h3><p>A balanced session prioritizing retrieval and application.</p></div></div><div class="study-session-steps">${methods.slice(0,5).map((m,i)=>`<div class="study-step"><span>${i+1}</span><div><b>${m.icon} ${esc(m.name)}</b><small>${esc(m.desc)}</small></div></div>`).join('')}</div></div>`;}
  function populateSubjects(){const opts=subjects().map(s=>`<option value="${esc(s.name)}">${esc(s.emoji||'📚')} ${esc(s.name)}</option>`).join('');['studyHomeSubject','studySetFilter'].forEach(id=>{const x=document.getElementById(id);if(!x)return;const cur=x.value;x.innerHTML='<option value="">All subjects</option>'+opts;if(cur&&[...x.options].some(o=>o.value===cur))x.value=cur;});}
  function renderPlans(){ensureData();const box=document.getElementById('studyPlans');if(!box)return;const d=data();if(!subjects().length){box.innerHTML='<div class="study-empty"><h3>No active subjects</h3><p>Add subjects first, then generate their study plans.</p></div>';return;}box.innerHTML=subjects().map(s=>{const ids=subjectProfile(s.name);return `<article class="study-plan-card"><div class="study-plan-heading"><span class="study-plan-icon">${esc(s.emoji||'📚')}</span><div><h3>${esc(s.name)}</h3><p>Recommended mix for this subject</p></div></div><div class="study-method-pills">${ids.map(id=>{const m=method(id);return `<span title="${esc(m.desc)}">${m.icon} ${esc(m.name)}</span>`;}).join('')}</div><div class="study-plan-routine"><b>Suggested session</b><span>Understand → ${method(ids[0])?.name} → Apply → Check errors → Schedule review</span></div><button class="secondary-button study-plan-save" data-subject="${esc(s.name)}">Save this plan</button></article>`;}).join('');box.querySelectorAll('.study-plan-save').forEach(b=>b.onclick=()=>savePlan(b.dataset.subject));}
  function savePlan(subject){ensureData();const d=data();const existing=d.studyPlans.find(p=>p.subject===subject);const plan={id:existing?.id||`SP-${Date.now()}`,subject,methods:subjectProfile(subject),createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(existing)Object.assign(existing,plan);else d.studyPlans.push(plan);savePlannerData?.();render();switchTab('plans');}
  function generatePlans(){ensureData();subjects().forEach(s=>{if(!data().studyPlans.some(p=>p.subject===s.name))data().studyPlans.push({id:`SP-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,subject:s.name,methods:subjectProfile(s.name),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});});savePlannerData?.();renderPlans();}
  function renderMethods(){const box=document.getElementById('studyMethods');if(!box)return;box.innerHTML=METHODS.map(m=>`<article class="study-method-card"><div class="study-method-icon">${m.icon}</div><div><div class="study-method-top"><h3>${esc(m.name)}</h3><span>${esc(m.strength)}</span></div><p>${esc(m.desc)}</p><small>Useful for: ${esc(m.best.join(' · '))}</small></div></article>`).join('');}
  function renderSets(){ensureData();const box=document.getElementById('studySets');if(!box)return;const f=document.getElementById('studySetFilter')?.value||'';const sets=data().studySets.filter(s=>!f||s.subject===f);if(!sets.length){box.innerHTML='<div class="study-empty"><div class="study-empty-icon">🧠</div><h3>No study sets yet</h3><p>Create flashcards, notes, or question banks and they will become part of your subject study plans.</p></div>';return;}box.innerHTML=sets.map(s=>`<article class="study-set-card"><div class="study-set-icon">${esc(subjects().find(x=>x.name===s.subject)?.emoji||'🧠')}</div><div class="study-set-main"><div class="study-set-top"><div><h3>${esc(s.name)}</h3><div class="study-set-meta">${esc(s.subject)} · ${esc(s.type)}</div></div><button class="study-delete-button" data-id="${esc(s.id)}">Delete</button></div><p>${esc(s.description||'Ready to add study material.')}</p><div class="study-set-footer"><span>${Array.isArray(s.items)?s.items.length:0} items</span><button class="secondary-button" disabled>Open set</button></div></div></article>`).join('');box.querySelectorAll('.study-delete-button').forEach(b=>b.onclick=()=>deleteSet(b.dataset.id));}
  function deleteSet(id){const d=data(),set=(d.studySets||[]).find(s=>String(s.id)===String(id));if(!set||!confirm(`Delete “${set.name}”? This cannot be undone.`))return;d.studySets=d.studySets.filter(s=>String(s.id)!==String(id));savePlannerData?.();renderSets();}
  function render(){ensureData();ensurePage();populateSubjects();const d=data();document.getElementById('studySetCount').textContent=d.studySets.length;document.getElementById('studyDueCount').textContent=d.studySets.reduce((n,s)=>n+(s.items||[]).filter(i=>i?.dueAt&&new Date(i.dueAt)<=new Date()).length,0);document.getElementById('studyPlanCount').textContent=d.studyPlans.length;renderToday();renderMethods();}
  window.renderStudy=render;window.generateStudyPlans=generatePlans;window.openStudyMethods=()=>switchTab('methods');
  window.addEventListener('planner-data-changed',()=>{if(document.getElementById('studyPage'))render();});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();
